delete from [dbo].[ResourceType]
delete from [dbo].[UserPassword];
delete from [dbo].[UserProperty];
delete from [dbo].[ResourceRole];
delete from [dbo].[Authorization];
delete from [dbo].[Domain];
delete from [dbo].[Role];
delete from [dbo].[User];
delete from [dbo].[Resource];
delete from [dbo].[Token];
delete from [dbo].[Translation];
delete from [dbo].[Language];
delete from [dbo].[ClientSetting];
delete from [dbo].[History];
delete from [dbo].[ServerSetting];
