@hostname = 2.236.112.207
@port = 19888
@protocol = http

### invoke a public api that return a GUID
GET {{protocol}}://{{hostname}}:{{port}}/sample.free.api
### invoke a private api that return a message composed with the username of the user in session
GET {{protocol}}://{{hostname}}:{{port}}/sample.private.api
### execute the login with username and password
POST {{protocol}}://{{hostname}}:{{port}}/system.login.api
Content-Type: application/json

{
    "username": "eca",
    "password": "password"
}
### execute the logout and terminate the session
GET {{protocol}}://{{hostname}}:{{port}}/system.logout.api
### request a token to be used to invoke method that need it. if reusable the token can survive all api call during the same session
POST {{protocol}}://{{hostname}}:{{port}}/system.token.api
Content-Type: application/json

{
    "isreusable": true
}
### check the token
GET {{protocol}}://{{hostname}}:{{port}}/system.check.api?t=03582c055ea24e91b895dd3385a49ab9a2458d71cdef4a6b92c48e89e0d94581
### return the list of domains related the user session
GET {{protocol}}://{{hostname}}:{{port}}/system.domains.api
### return the list of rules related with the user session and the specific domain
POST {{protocol}}://{{hostname}}:{{port}}/system.roles.api
Content-Type: application/json

{
    "domain": "domain a"
}
### return user information
GET {{protocol}}://{{hostname}}:{{port}}/system.info.api?t=0579d0a40b2a427183a5d0f8c2c96b0146248eb8408e49b2a29e792997db3cd7
### set the current user in session
POST {{protocol}}://{{hostname}}:{{port}}/system.domain.api?t=0579d0a40b2a427183a5d0f8c2c96b0146248eb8408e49b2a29e792997db3cd7
Content-Type: application/json

{
    "domain": "domain a"
}
### return the list of resource related to the user in session
GET {{protocol}}://{{hostname}}:{{port}}/system.resources.api
### return the list of languages supported
GET {{protocol}}://{{hostname}}:{{port}}/system.languages.api
### return the list of messages in the specified language
GET {{protocol}}://{{hostname}}:{{port}}/system.translations.api?language=it
### get a user from a reset token
GET {{protocol}}://{{hostname}}:{{port}}/system.userresettoken.api?token=dbe67d4c-c6ee-4add-b344-98ceb73f15ae
### set a password with a reset token
POST {{protocol}}://{{hostname}}:{{port}}/system.resetpassword.api
Content-Type: application/json

{
    "token": "dbe67d4c-c6ee-4add-b344-98ceb73f15ae",
    "password": "password"
}
### get the reset token starting from an email
GET {{protocol}}://{{hostname}}:{{port}}/system.setresettoken.api?email=emiliano.carlesi@gmail.com