@hostname = localhost
@protocol = https
@port = 47084

@token = edeee1972d3c48cd97f1627c88c2c3ffc69fa7cc5b944502988d30517e77b888

### invoke a public api that return a GUID
GET {{protocol}}://{{hostname}}:{{port}}/sample.free.api
### invoke a private api that return a message composed with the username of the user in session
GET {{protocol}}://{{hostname}}:{{port}}/sample.private.api
### initialize the session
GET {{protocol}}://{{hostname}}:{{port}}/system.init.api
### execute the login with username and password
POST {{protocol}}://{{hostname}}:{{port}}/system.login.api
Content-Type: application/json

{
    "username": "eca",
    "password": "password"
}
### change password
### username is optional, if not specified us the session user
POST {{protocol}}://{{hostname}}:{{port}}/system.password.api
Content-Type: application/json

{
    "username": "eca",
    "old": "password",
    "new": "password.1",
    "confirm": "password.1"
}
### execute the logout and terminate the session
GET {{protocol}}://{{hostname}}:{{port}}/system.logout.api
### set and delete user property
POST {{protocol}}://{{hostname}}:{{port}}/system.property.api
Content-Type: application/json

{
    "name": "Property 2",
    "value": ""
}
### request a token to be used to invoke method that need it. if reusable the token can survive all api call during the same session
POST {{protocol}}://{{hostname}}:{{port}}/system.token.api
Content-Type: application/json

{
    "isreusable": true
}
### check the token
GET {{protocol}}://{{hostname}}:{{port}}/system.check.api
ZestyApiToken: {{token}}
### return the list of domains related the user session
GET {{protocol}}://{{hostname}}:{{port}}/system.domains.api
### return the list of rules related with the user session and the specific domain
POST {{protocol}}://{{hostname}}:{{port}}/system.roles.api
Content-Type: application/json

{
    "domain": "bc89e749-784b-479f-91e6-85708326558e"
}
### return user information
GET {{protocol}}://{{hostname}}:{{port}}/system.info.api
ZestyApiToken: {{token}}
### set the current user in session
POST {{protocol}}://{{hostname}}:{{port}}/system.domain.api
Content-Type: application/json

{
    "domain": "bc89e749-784b-479f-91e6-85708326558e"
}
### return the list of resource related to the user in session
GET {{protocol}}://{{hostname}}:{{port}}/system.resources.api
### return the list of languages supported
GET {{protocol}}://{{hostname}}:{{port}}/system.languages.api
### return the list of messages in the specified language
GET {{protocol}}://{{hostname}}:{{port}}/system.translations.api?language=it
### get a user from a reset token
GET {{protocol}}://{{hostname}}:{{port}}/system.userresettoken.api?token=9658ffba-922a-4d7d-91b8-540fbcecf871
### set a password with a reset token
POST {{protocol}}://{{hostname}}:{{port}}/system.resetpassword.api
Content-Type: application/json

{
    "token": "9658ffba-922a-4d7d-91b8-540fbcecf871",
    "password": "password"
}
### get the reset token starting from an email
GET {{protocol}}://{{hostname}}:{{port}}/system.setresettoken.api?email=emiliano.carlesi@gmail.com
### get the client settings
GET {{protocol}}://{{hostname}}:{{port}}/system.clientsettings.api

### add a user
POST {{protocol}}://{{hostname}}:{{port}}/system.admin.user.add.api
Content-Type: application/json

{
    "username": "mrosso",
    "email": "mrosso666@gmail.com",
    "firstname": "Mario",
    "lastname": "Rossi"
}

### delete a user
DELETE {{protocol}}://{{hostname}}:{{port}}/system.admin.user.delete.api?id=5984add5-e473-49ad-bd66-dcea2fa5cce1

### hard delete a user
DELETE {{protocol}}://{{hostname}}:{{port}}/system.admin.user.harddelete.api?id=5984add5-e473-49ad-bd66-dcea2fa5cce1

### get the list of users
GET {{protocol}}://{{hostname}}:{{port}}/system.admin.user.list.api

### get a user
GET {{protocol}}://{{hostname}}:{{port}}/system.admin.user.get.api?id=5984add5-e473-49ad-bd66-dcea2fa5cce1

### add a user
POST {{protocol}}://{{hostname}}:{{port}}/system.admin.user.update.api
Content-Type: application/json

{
    "id": "5984add5-e473-49ad-bd66-dcea2fa5cce1",
    "username": "mrosso",
    "email": "mrosso@gmail.com",
    "firstname": "Mario",
    "lastname": "Rosso"
}

### authorize a user
POST {{protocol}}://{{hostname}}:{{port}}/system.admin.user.authorize.api
Content-Type: application/json

{
    "user": "5984add5-e473-49ad-bd66-dcea2fa5cce1",
    "domain" : "bc89e749-784b-479f-91e6-85708326558e",
    "role" : "62ef76b8-e39e-41c7-86dc-4801642dc655"
}

### deauthorize a user
POST {{protocol}}://{{hostname}}:{{port}}/system.admin.user.deauthorize.api
Content-Type: application/json

{
    "user": "5984add5-e473-49ad-bd66-dcea2fa5cce1",
    "domain" : "bc89e749-784b-479f-91e6-85708326558e",
    "role" : "62ef76b8-e39e-41c7-86dc-4801642dc655"
}

### get the list of roles
GET {{protocol}}://{{hostname}}:{{port}}/system.admin.role.list.api
### get the list of domains
GET {{protocol}}://{{hostname}}:{{port}}/system.admin.domain.list.api
### add domain
POST {{protocol}}://{{hostname}}:{{port}}/system.admin.domain.add.api
Content-Type: application/json

{
    "name" : "test domain 1",
    "parent" : ""
}
### add role
POST {{protocol}}://{{hostname}}:{{port}}/system.admin.role.add.api
Content-Type: application/json

{
    "name" : "test role 1",
}
### get the list of resources
GET {{protocol}}://{{hostname}}:{{port}}/system.admin.resource.list.api
### get the list of grants
GET {{protocol}}://{{hostname}}:{{port}}/system.admin.resource.grants.api?r=62ef76b8-e39e-41c7-86dc-4801642dc655
### authorize resource
POST {{protocol}}://{{hostname}}:{{port}}/system.admin.resource.authorize.api
Content-Type: application/json

{
    "resource" : "b01826ba-d5ab-4d0f-a78d-02bc5cad5da4",
    "role" : "b01826ba-d5ab-4d0f-a78d-02bc5cad5da4"
}
### deauthorize resource
POST {{protocol}}://{{hostname}}:{{port}}/system.admin.resource.deauthorize.api
Content-Type: application/json

{
    "resource" : "b01826ba-d5ab-4d0f-a78d-02bc5cad5da4",
    "role" : "b01826ba-d5ab-4d0f-a78d-02bc5cad5da4"
}
